[package]
description = "Test utilities for ferrous-owl LSP decoration tests"
edition = "2021"
name = "owl-test"
publish = false
version = "0.1.0"

[dependencies]
ferrous-owl = { path = "../" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
wait-timeout = "0.2"
